#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2026-present ROCKNIX (https://github.com/ROCKNIX)

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PKG_DIR=$(CDPATH= cd -- "${SCRIPT_DIR}/.." && pwd)
REPO_ROOT=$(CDPATH= cd -- "${PKG_DIR}/../../../../.." && pwd)

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

check_script() {
  path=$1
  [ -f "${path}" ] || fail "missing script: ${path}"
  [ -x "${path}" ] || fail "script is not executable: ${path}"
  sh -n "${path}" || fail "shell syntax failed: ${path}"
}

check_script "${PKG_DIR}/scripts/nix-doctor"
check_script "${PKG_DIR}/scripts/nix-layer-activate"
check_script "${PKG_DIR}/scripts/nixctl"

[ -f "${PKG_DIR}/package.mk" ] || fail "missing package.mk"
sh -n "${PKG_DIR}/package.mk" || fail "package.mk syntax failed"
grep -q 'PKG_NAME="nix-integration"' "${PKG_DIR}/package.mk" || fail "package.mk has wrong PKG_NAME"
grep -q 'PKG_TOOLCHAIN="manual"' "${PKG_DIR}/package.mk" || fail "package.mk should use manual toolchain"
! grep -q 'nix-portable' "${PKG_DIR}/package.mk" || fail "package.mk must not ship nix-portable tooling on image-first builds"
grep -q 'nix-doctor' "${PKG_DIR}/package.mk" || fail "package.mk does not install nix-doctor"
grep -q 'nix-layer-activate' "${PKG_DIR}/package.mk" || fail "package.mk does not install nix-layer-activate (Layer 6 activation engine)"
grep -q 'nixctl' "${PKG_DIR}/package.mk" || fail "package.mk does not install nixctl (Layer 4 front door)"
grep -q '/usr/lib/nix-integration/tests' "${PKG_DIR}/package.mk" || fail "package.mk does not install nix-integration smoke tests"
grep -q 'nix-integration-runtime-smoke.sh' "${PKG_DIR}/package.mk" || fail "package.mk does not package runtime smoke helper"
grep -q 'mkdir -p ${INSTALL}/nix' "${PKG_DIR}/package.mk" || fail "package.mk does not create /nix mountpoint"
grep -q 'enable_service nix-storage-setup.service' "${PKG_DIR}/package.mk" || fail "package.mk does not enable nix-storage-setup.service"
grep -q 'enable_service nix.mount' "${PKG_DIR}/package.mk" || fail "package.mk does not enable nix.mount"
grep -q 'NIX_DAEMON_SUPPORT=' "${PKG_DIR}/package.mk" || fail "package.mk missing opt-in Layer 8 daemon support gate"
grep -q 'add_group "${NIX_DAEMON_BUILD_GROUP}"' "${PKG_DIR}/package.mk" || fail "package.mk missing image-time nix daemon build group"
grep -q 'add_user "nixbld${i}"' "${PKG_DIR}/package.mk" || fail "package.mk missing image-time nix daemon build users"
grep -q 'NIX_DAEMON_BUILD_USER_COUNT=' "${PKG_DIR}/package.mk" || fail "package.mk missing daemon build user count"

PROFILE_SNIPPET="998-nix-integration.conf"
[ -f "${PKG_DIR}/profile.d/${PROFILE_SNIPPET}" ] || fail "missing profile integration"
sh -n "${PKG_DIR}/profile.d/${PROFILE_SNIPPET}" || fail "profile integration syntax failed"
! grep -q 'NP_RUNTIME' "${PKG_DIR}/profile.d/${PROFILE_SNIPPET}" || fail "profile.d must not configure nix-portable runtime"
grep -q '/nix/var/nix/profiles/default/bin' "${PKG_DIR}/profile.d/${PROFILE_SNIPPET}" || fail "profile.d missing Layer 4 PATH prefix (/nix/var/nix/profiles/default/bin)"
grep -q '\.nix-profile/bin' "${PKG_DIR}/profile.d/${PROFILE_SNIPPET}" || fail "profile.d missing Layer 5 PATH prefix (~/.nix-profile/bin)"
grep -q 'Layer 5: persistent Nix profiles' "${PKG_DIR}/profile.d/${PROFILE_SNIPPET}" || fail "profile.d missing Layer 5 profile contract documentation"

# ROCKNIX's /etc/profile.d/098-busybox resets PATH. The Nix profile snippet
# must sort after it, or the Layer 4/5 PATH prefixes are clobbered in login
# shells. This guards the exact issue found during first image validation.
case "${PROFILE_SNIPPET}" in
  99*|[1-9][0-9][0-9]*) ;;
  *) fail "profile snippet must sort after 098-busybox so PATH is not reset later: ${PROFILE_SNIPPET}" ;;
esac

# Verify nixctl declares the canonical subcommands and pinned-version constants.
grep -q 'NIX_VERSION_PINNED=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing NIX_VERSION_PINNED constant"
grep -q 'NIX_TARBALL_SHA256_PINNED=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing NIX_TARBALL_SHA256_PINNED constant"
grep -q 'NIX_USER_PROFILE_BIN=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 5 profile bin constant"
grep -q 'Layer 5 (persistent profile) status' "${PKG_DIR}/scripts/nixctl" || fail "nixctl status missing Layer 5 section"
grep -q 'print_profile_conflicts' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 5 conflict reporting"
grep -q 'is_expected_nix_tool_shadow' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing expected Nix tool shadow allowlist"
grep -q 'check_layer5' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 5 checks"
grep -q 'check_profile_command_conflicts' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 5 conflict checks"
grep -q 'is_expected_nix_tool_shadow' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing expected Nix tool shadow allowlist"
grep -q 'Layer 6 (managed user environment) status' "${PKG_DIR}/scripts/nixctl" || fail "nixctl status missing Layer 6 section"
grep -q 'cmd_user_env' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 6 user-env dispatch"
grep -q 'check_layer6' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 6 checks"
grep -q 'Layer 6 source missing' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 6 missing source/store-path checks"
grep -q 'Layer 7 (app/UI experiment) status' "${PKG_DIR}/scripts/nixctl" || fail "nixctl status missing Layer 7 section"
grep -q 'layer7_binary_is_nix_backed' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 7 Nix-backed binary origin check"
grep -q 'check_layer7' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 7 checks"
grep -q 'Layer 7 ready' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 7 readiness output"
grep -q 'Layer 8 (experimental daemon) status' "${PKG_DIR}/scripts/nixctl" || fail "nixctl status missing Layer 8 section"
grep -q 'print_layer8_status' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 8 status reporter"
grep -q 'cmd_daemon' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 8 daemon lifecycle dispatch"
grep -q 'daemon preflight failed' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 8 daemon preflight gate"
grep -q 'Layer 8 daemon mode disabled' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 8 daemon disable path"
grep -q 'check_layer8' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 8 checks"
grep -q 'Layer 8 daemon eligibility' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 8 eligibility output"
grep -q 'Layer 4 single-user/root Nix remains' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 8 fallback guidance"
grep -q 'NIX_GROUP_FILE=' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing fixtureable group file for Layer 8"
grep -q 'NIX_GROUP_FILE=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixtureable group file for Layer 8"
grep -q 'Layer 9 (nspawn guest proof) status' "${PKG_DIR}/scripts/nixctl" || fail "nixctl status missing Layer 9 section"
grep -q 'print_layer9_status' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 9 status reporter"
grep -q 'layer9_eligibility' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 9 eligibility reporter"
grep -q 'check_layer9' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 9 checks"
grep -q 'Layer 9 nspawn eligibility' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 9 eligibility output"
grep -q 'NIX_LAYER9_NSPAWN_BIN=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixtureable nspawn binary for Layer 9"
grep -q 'NIX_LAYER9_NSPAWN_BIN=' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing fixtureable nspawn binary for Layer 9"
grep -q 'NIX_LAYER9_GUEST_ROOT=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixtureable guest root for Layer 9"
grep -q 'NIX_LAYER9_GUEST_ROOT=' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing fixtureable guest root for Layer 9"
grep -q 'NIX_LAYER9_SKIP_KERNEL_CHECK=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixtureable kernel check override for Layer 9"
grep -q 'NIX_LAYER9_SKIP_KERNEL_CHECK=' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing fixtureable kernel check override for Layer 9"
grep -q 'Layer 10 (managed nspawn guest operations) status' "${PKG_DIR}/scripts/nixctl" || fail "nixctl status missing Layer 10 section"
grep -q 'cmd_guest' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 guest dispatch"
grep -q 'layer10_rootfs_mode' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 rootfs mode detection"
grep -q 'layer10_root_executable' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 guest-local executable detection"
grep -q 'Layer 10 guest preflight passed' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 guest preflight"
grep -q 'cmd_guest_init' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 guest proof init"
grep -q 'cmd_guest_import' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10b bootable import"
grep -q 'guest import --bootable' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10b import command text"
grep -q 'rootfs-provenance' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10b provenance metadata"
grep -q 'archive contains unsafe paths' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10b archive safety guard"
grep -q 'layer10_list_archive' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10b compression-aware archive listing"
grep -q 'cmd_guest_run' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 guest run"
grep -q 'cmd_guest_shell' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 guest shell"
grep -q 'cmd_guest_start' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 guest start"
grep -q 'cmd_guest_stop' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 guest stop"
grep -q 'cmd_guest_cleanup' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 guest cleanup"
grep -q -- '--register=no' "${PKG_DIR}/scripts/nixctl" || fail "nixctl Layer 10 guest run must avoid machined registration"
grep -q 'guest cleanup: refusing unsafe guest root' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 unsafe cleanup guard"
grep -q 'CPUWeight=${NIX_LAYER10_CPU_WEIGHT}' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 CPUWeight resource policy"
grep -q 'MemoryMax=${NIX_LAYER10_MEMORY_MAX}' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 MemoryMax resource policy"
! grep -q 'systemctl.*enable.*rocknix-guest' "${PKG_DIR}/scripts/nixctl" || fail "nixctl must not enable Layer 10 guest units"
grep -q 'NIX_LAYER10_TIMEOUT=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixtureable Layer 10 timeout"
grep -q 'NIX_LAYER10_START_WAIT=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixtureable Layer 10 start wait"
grep -q 'layer10_process_running' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing root-specific Layer 10 process evidence"
grep -q 'no nspawn process references' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 10 start live-evidence failure"
grep -q 'check_layer10' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 10 checks"
grep -q 'Layer 10 guest eligibility' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 10 eligibility output"
grep -q 'Layer 10 bootable provenance' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 10b provenance reporting"
grep -q 'layer10_process_running' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing root-specific Layer 10 process evidence"
grep -q 'unit is active but no nspawn process references' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 10 active-unit/no-process failure"
grep -q 'NIX_LAYER10_STATE_DIR=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixtureable Layer 10 state dir"
grep -q 'NIX_LAYER10_STATE_DIR=' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing fixtureable Layer 10 state dir"
grep -q 'NIX_LAYER10_GUEST_ROOT=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixtureable Layer 10 guest root"
grep -q 'NIX_LAYER10_GUEST_ROOT=' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing fixtureable Layer 10 guest root"
grep -q 'NIX_LAYER10_UNIT_NAME=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixtureable Layer 10 unit name"
grep -q 'NIX_LAYER10_UNIT_NAME=' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing fixtureable Layer 10 unit name"
grep -q 'Layer 11 (one-shot guest-backed bridges) status' "${PKG_DIR}/scripts/nixctl" || fail "nixctl status missing Layer 11 section"
grep -q 'cmd_bridge' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 11 bridge dispatch"
grep -q 'Layer 11 bridge preflight passed' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 11 bridge preflight"
grep -q 'cmd_bridge_install' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 11 bridge install"
grep -q 'cmd_bridge_remove' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 11 bridge remove"
grep -q 'cmd_bridge_run' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 11 bridge run"
grep -q 'target exists and is not owned by Layer 11' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 11 conflict refusal"
grep -q 'refusing unsafe target path' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 11 unsafe target guard"
grep -q 'bridge run' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 11 wrapper run path"
grep -q 'NIX_LAYER11_STATE_DIR=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixtureable Layer 11 state dir"
grep -q 'NIX_LAYER11_BIN_DIR=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixtureable Layer 11 bin dir"
grep -q 'NIX_LAYER11_NIXCTL_BIN=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixtureable Layer 11 nixctl bin"
grep -q 'NIX_LAYER11_STATE_DIR=' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing fixtureable Layer 11 state dir"
grep -q 'NIX_LAYER11_BIN_DIR=' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing fixtureable Layer 11 bin dir"
grep -q 'check_layer11' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 11 checks"
grep -q 'Layer 11 bridge eligibility' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 11 eligibility output"
grep -q 'NIX_LAYER12_STATE_DIR=' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixtureable Layer 12 state dir"
grep -q 'NIX_LAYER12_STATE_DIR=' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing fixtureable Layer 12 state dir"
grep -q 'Layer 12 (opt-in guest SSH) status' "${PKG_DIR}/scripts/nixctl" || fail "nixctl status missing Layer 12 section"
grep -q 'cmd_guest_service' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 12 guest service dispatch"
grep -q 'guest service enable ssh' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 12 SSH enable command"
grep -q 'refusing unsafe port: ${port}' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 12 port guard"
grep -q -- '--private-network' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing private networking for bootable guest"
grep -q 'layer10_nspawn_network_args' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 12 shared-network switch"
if grep -q -- '--port=tcp:%s:22' "${PKG_DIR}/scripts/nixctl"; then
  fail "nixctl must not depend on systemd-nspawn --port NAT for Layer 12"
fi
grep -q 'currently supports only port' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing fixed guest SSH port guard"
grep -q -- '--bind-ro=%s:%s' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 12 authorized-keys bind"
grep -R -q 'ports = \[ 2222 \];' "${PKG_DIR}/guest" || fail "guest config must listen on Layer 12 default SSH port 2222"
grep -q 'root/etc/ssh/authorized_keys.d/root' "${PKG_DIR}/guest/flake.nix" || fail "guest rootfs must provide regular authorized_keys target for StrictModes"
grep -q 'root/usr/bin/nix' "${PKG_DIR}/guest/flake.nix" || fail "guest rootfs must expose /usr/bin/nix for bridge/smoke contracts"
grep -q 'check_layer12' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 12 checks"

grep -q 'Layer 13 (declarative modules) status' "${PKG_DIR}/scripts/nixctl" || fail "nixctl status missing Layer 13 section"
grep -q 'cmd_module' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 13 module command dispatch"
grep -q 'lib.evalModules' "${PKG_DIR}/modules/lib/eval-rocknix.nix" || fail "Layer 13 evaluator must use the Nix module system"
grep -q 'layer13_manifest_preflight' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing Layer 13 manifest preflight"
grep -q 'check_layer13' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 13 checks"
grep -q 'modules/flake.nix' "${PKG_DIR}/package.mk" || grep -q 'usr/lib/nix-integration/modules' "${PKG_DIR}/package.mk" || fail "package.mk must install Layer 13 module kit"
grep -q 'guest module' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing guest module workspace commands"
grep -q 'profiles/ssh.nix' "${PKG_DIR}/guest/rocknix-guest.nix" || fail "guest default config must import modular profile"
grep -q 'LAYER13' "${PKG_DIR}/tests/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 13 fixture coverage"
grep -q 'Layer 12 guest SSH eligibility' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 12 eligibility output"
grep -q 'must not bind host port 22' "${PKG_DIR}/scripts/nix-doctor" || fail "nix-doctor missing Layer 12 port 22 guardrail"
grep -q 'LAYER12_SMOKE=ssh' "${PKG_DIR}/tests/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 12 SSH mode"
grep -q 'Layer 12 guest SSH did not return nix version' "${PKG_DIR}/tests/nix-integration-runtime-smoke.sh" || fail "Layer 12 smoke must execute a real SSH command"
for sub in status install upgrade uninstall doctor user-env daemon guest bridge; do
  # Subcommand can appear as 'sub)' (alone), 'sub|other)' (left of alt),
  # or '...|sub)' (right of alt). Match by requiring sub to be preceded by
  # start-of-line, whitespace, or '|' and followed by ')' or '|'.
  grep -qE "(^|[[:space:]]|\|)${sub}[|)]" "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing dispatch for subcommand: ${sub}"
done

grep -q 'surface|name|source|mode' "${PKG_DIR}/scripts/nix-layer-activate" || fail "nix-layer-activate missing manifest contract"
grep -q 'target exists and is not owned by Layer 6' "${PKG_DIR}/scripts/nix-layer-activate" || fail "nix-layer-activate missing conflict refusal"
[ -f "${PKG_DIR}/docs/layer6-activation-contract.md" ] || fail "missing Layer 6 activation contract doc"
grep -q '/storage/bin' "${PKG_DIR}/docs/layer6-activation-contract.md" || fail "Layer 6 contract missing storage bin surface"
grep -q '/storage/.config/profile.d' "${PKG_DIR}/docs/layer6-activation-contract.md" || fail "Layer 6 contract missing profile.d surface"
[ -f "${PKG_DIR}/docs/layer7-app-experiment-contract.md" ] || fail "missing Layer 7 app experiment contract doc"
grep -q 'standard `nix profile`' "${PKG_DIR}/docs/layer7-app-experiment-contract.md" || fail "Layer 7 contract missing standard nix profile split"
grep -q '/storage/.local/share/nix-apps/layer7' "${PKG_DIR}/docs/layer7-app-experiment-contract.md" || fail "Layer 7 contract missing safe app state root"
grep -q '/storage/.cache/nix-apps/layer7' "${PKG_DIR}/docs/layer7-app-experiment-contract.md" || fail "Layer 7 contract missing safe app cache root"
grep -q 'Nix-backed binary' "${PKG_DIR}/docs/layer7-app-experiment-contract.md" || fail "Layer 7 contract missing Nix-backed binary proof"
[ -f "${PKG_DIR}/docs/layer9-nspawn-guest-contract.md" ] || fail "missing Layer 9 nspawn guest contract doc"
grep -q '/storage/machines/rocknix-guest' "${PKG_DIR}/docs/layer9-nspawn-guest-contract.md" || fail "Layer 9 contract missing guest root path"
grep -q '/dev/dri' "${PKG_DIR}/docs/layer9-nspawn-guest-contract.md" || fail "Layer 9 contract missing GPU passthrough prohibition"
grep -q 'PipeWire' "${PKG_DIR}/docs/layer9-nspawn-guest-contract.md" || fail "Layer 9 contract missing audio passthrough prohibition"
grep -q '/dev/input' "${PKG_DIR}/docs/layer9-nspawn-guest-contract.md" || fail "Layer 9 contract missing input passthrough prohibition"
grep -q 'Fallback does' "${PKG_DIR}/docs/layer9-nspawn-guest-contract.md" || fail "Layer 9 contract missing fallback boundary"
grep -q 'Guest state can be stopped and removed without touching host Nix state' "${PKG_DIR}/docs/layer9-nspawn-guest-contract.md" || fail "Layer 9 contract missing cleanup boundary"
[ -f "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" ] || fail "missing Layer 10 guest lifecycle contract doc"
grep -q '/storage/.config/nix-integration/layer10' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10 contract missing state dir path"
grep -q '/storage/machines/rocknix-guest' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10 contract missing guest root path"
grep -q -- '--register=no' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10 contract missing no-machined nspawn flag"
grep -q 'machinectl' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10 contract missing no machinectl dependency"
grep -q 'proof' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10 contract missing proof rootfs mode"
grep -q 'bootable' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10 contract missing bootable rootfs mode"
grep -q 'must not call `systemctl enable`' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10 contract missing no-autostart policy"
grep -q '/dev/dri' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10 contract missing GPU passthrough prohibition"
grep -q 'PipeWire' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10 contract missing audio passthrough prohibition"
grep -q '/dev/input' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10 contract missing input passthrough prohibition"
grep -q 'Layer 10b bootable rootfs artifact boundary' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10 contract missing Layer 10b bootable artifact boundary"
grep -q 'source/provenance, sha256, imported timestamp' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10b contract missing provenance/checksum metadata rule"
grep -q 'must not depend on binding host `/nix`' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10b contract missing first-validation host /nix sharing prohibition"
grep -q 'no guest SSH, password login, default credentials' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10b contract missing guest SSH/default credential prohibition"
grep -q 'minimal init fixture.*not sufficient hardware evidence' "${PKG_DIR}/docs/layer10-guest-lifecycle-contract.md" || fail "Layer 10b contract must distinguish fixtures from hardware Go"
grep -q '| 10b | Bootable guest rootfs validation' "${REPO_ROOT}/docs/plans/2026-04-28-001-feat-layered-nix-integration-plan.md" || fail "roadmap missing Layer 10b row"
[ -f "${PKG_DIR}/guest/README.md" ] || fail "missing Layer 10b guest README"
[ -f "${PKG_DIR}/guest/rocknix-guest.nix" ] || fail "missing Layer 10b guest NixOS module"
[ -f "${PKG_DIR}/guest/flake.nix" ] || fail "missing Layer 10b guest flake"
[ -f "${PKG_DIR}/guest/flake.lock" ] || fail "missing Layer 10b guest flake lock"
grep -q 'targetSystem = "aarch64-linux"' "${PKG_DIR}/guest/flake.nix" || fail "Layer 10b guest flake must target aarch64-linux"
grep -q 'x86_64-linux' "${PKG_DIR}/guest/flake.nix" || fail "Layer 10b guest flake must expose an x86_64 host build package"
grep -q 'nixos-25.11' "${PKG_DIR}/guest/flake.nix" || fail "Layer 10b guest flake must pin nixpkgs release input"
grep -R -q 'boot.isContainer = true' "${PKG_DIR}/guest" || fail "Layer 10b guest must be a container-style rootfs"
grep -R -q 'services.openssh = {' "${PKG_DIR}/guest" || fail "Layer 12 guest must define locked-down OpenSSH"
grep -R -q 'authorizedKeysFiles = \[ "/etc/ssh/authorized_keys.d/%u" \]' "${PKG_DIR}/guest" || fail "Layer 12 guest must use runtime-mounted authorized keys"
grep -R -q 'PasswordAuthentication = false' "${PKG_DIR}/guest" || fail "Layer 12 guest must disable SSH password authentication"
grep -R -q 'KbdInteractiveAuthentication = false' "${PKG_DIR}/guest" || fail "Layer 12 guest must disable keyboard-interactive authentication"
grep -R -q 'PermitRootLogin = "prohibit-password"' "${PKG_DIR}/guest" || fail "Layer 12 guest root SSH must be key-only"
grep -R -q 'users.users.root.hashedPassword = "!"' "${PKG_DIR}/guest" || fail "Layer 10b guest must lock root password"
! grep -R -q 'ssh-rsa\|ssh-ed25519\|ecdsa-sha2-' "${PKG_DIR}/guest" || fail "Layer 12 guest must not ship authorized keys"
! grep -R --include='*.nix' -q '/dev/dri\|PipeWire\|PulseAudio\|/dev/input\|Steam\|FEX\|WAYLAND_DISPLAY' "${PKG_DIR}/guest" || fail "Layer 10b guest must not reference forbidden passthrough surfaces"
grep -q 'sha256sum result/tarball' "${PKG_DIR}/guest/README.md" || fail "Layer 10b guest README must document artifact checksum capture"
grep -q 'free of default passwords' "${PKG_DIR}/guest/README.md" || fail "Layer 10b guest README must document credential boundary"
grep -q 'Layer 12' "${PKG_DIR}/guest/README.md" || fail "Layer 12 guest README must document opt-in SSH boundary"
[ -f "${PKG_DIR}/docs/layer11-bridge-contract.md" ] || fail "missing Layer 11 bridge contract doc"
grep -q '/storage/.config/nix-integration/layer11' "${PKG_DIR}/docs/layer11-bridge-contract.md" || fail "Layer 11 contract missing state dir path"
grep -q '/storage/bin' "${PKG_DIR}/docs/layer11-bridge-contract.md" || fail "Layer 11 contract missing storage bin target surface"
grep -q 'nixctl guest run' "${PKG_DIR}/docs/layer11-bridge-contract.md" || fail "Layer 11 contract missing Layer 10 guest run dependency"
grep -q 'one-shot bridges only' "${PKG_DIR}/docs/layer11-bridge-contract.md" || fail "Layer 11 contract missing one-shot scope"
grep -q 'must not.*guest SSH' "${PKG_DIR}/docs/layer11-bridge-contract.md" || fail "Layer 11 contract missing guest SSH prohibition"
grep -q 'must not.*systemd service' "${PKG_DIR}/docs/layer11-bridge-contract.md" || fail "Layer 11 contract missing no service/autostart policy"
grep -q '/dev/input' "${PKG_DIR}/docs/layer11-bridge-contract.md" || fail "Layer 11 contract missing input passthrough prohibition"
grep -q 'no guest process remains' "${PKG_DIR}/docs/layer11-bridge-contract.md" || fail "Layer 11 contract missing no residual guest process rule"
[ -f "${PKG_DIR}/system.d/nix-storage-setup.service" ] || fail "missing nix-storage-setup.service"
[ -f "${PKG_DIR}/system.d/nix.mount" ] || fail "missing nix.mount"
[ -f "${PKG_DIR}/system.d/nix-daemon.socket" ] || fail "missing Layer 8 nix-daemon.socket"
[ -f "${PKG_DIR}/system.d/nix-daemon.service" ] || fail "missing Layer 8 nix-daemon.service"
grep -q 'RequiresMountsFor=/storage' "${PKG_DIR}/system.d/nix-storage-setup.service" || fail "setup service does not require /storage"
grep -q '/storage/.nix-root' "${PKG_DIR}/system.d/nix-storage-setup.service" || fail "setup service does not prepare storage-backed Nix root"
grep -q 'DefaultDependencies=no' "${PKG_DIR}/system.d/nix.mount" || fail "nix.mount should avoid early local-fs ordering"
grep -q 'What=/storage/.nix-root' "${PKG_DIR}/system.d/nix.mount" || fail "nix.mount has wrong source"
grep -q 'Where=/nix' "${PKG_DIR}/system.d/nix.mount" || fail "nix.mount has wrong target"
grep -q 'Options=bind' "${PKG_DIR}/system.d/nix.mount" || fail "nix.mount is not a bind mount"
grep -q 'Before=nix-daemon.service' "${PKG_DIR}/system.d/nix.mount" || fail "nix.mount must order before nix-daemon.service"
grep -q 'Requires=nix.mount' "${PKG_DIR}/system.d/nix-daemon.socket" || fail "nix-daemon.socket must require nix.mount"
grep -q 'After=nix.mount' "${PKG_DIR}/system.d/nix-daemon.socket" || fail "nix-daemon.socket must start after nix.mount"
grep -q 'ConditionPathIsMountPoint=/nix' "${PKG_DIR}/system.d/nix-daemon.socket" || fail "nix-daemon.socket must require mounted /nix"
grep -q 'ListenStream=/nix/var/nix/daemon-socket/socket' "${PKG_DIR}/system.d/nix-daemon.socket" || fail "nix-daemon.socket has wrong socket path"
grep -q 'Requires=nix.mount' "${PKG_DIR}/system.d/nix-daemon.service" || fail "nix-daemon.service must require nix.mount"
grep -q 'After=nix.mount' "${PKG_DIR}/system.d/nix-daemon.service" || fail "nix-daemon.service must start after nix.mount"
grep -q 'ConditionPathIsMountPoint=/nix' "${PKG_DIR}/system.d/nix-daemon.service" || fail "nix-daemon.service must require mounted /nix"
grep -q 'NIX_CONF_DIR=/storage/.config/nix-daemon' "${PKG_DIR}/system.d/nix-daemon.service" || fail "nix-daemon.service missing storage-backed config path"
grep -q 'ExecStart=/nix/var/nix/profiles/default/bin/nix-daemon --daemon' "${PKG_DIR}/system.d/nix-daemon.service" || fail "nix-daemon.service has wrong ExecStart"
! grep -q 'enable_service nix-daemon' "${PKG_DIR}/package.mk" || fail "package.mk must not enable Layer 8 daemon units by default"

SYSTEMD_PKG="${REPO_ROOT}/projects/ROCKNIX/packages/sysutils/systemd/package.mk"
[ -f "${SYSTEMD_PKG}" ] || fail "missing ROCKNIX systemd package.mk"
grep -q 'NIX_INTEGRATION_SUPPORT=' "${REPO_ROOT}/projects/ROCKNIX/options" || fail "missing NIX_INTEGRATION_SUPPORT build option"
grep -q 'NIX_NSPAWN_SUPPORT=' "${REPO_ROOT}/projects/ROCKNIX/options" || fail "missing NIX_NSPAWN_SUPPORT build option"
grep -q 'nix-integration' "${REPO_ROOT}/projects/ROCKNIX/packages/virtual/image/package.mk" || fail "image package does not include nix-integration gate"
grep -q 'NIX_NSPAWN_SUPPORT=' "${SYSTEMD_PKG}" || fail "systemd package missing Layer 9 nspawn support gate"
grep -q 'if \[ "${NIX_NSPAWN_SUPPORT}" != "yes" \]' "${SYSTEMD_PKG}" || fail "systemd package must remove nspawn only when Layer 9 support is disabled"
grep -q 'safe_remove ${INSTALL}/usr/bin/systemd-nspawn' "${SYSTEMD_PKG}" || fail "systemd package missing nspawn binary removal fallback"
grep -q 'safe_remove ${INSTALL}/usr/lib/systemd/system/systemd-nspawn@.service' "${SYSTEMD_PKG}" || fail "systemd package missing nspawn unit removal fallback"
! grep -qE 'enable_service .*nspawn' "${SYSTEMD_PKG}" || fail "systemd package must not enable nspawn services by default"

[ ! -e "${REPO_ROOT}/nix-on-rocknix-bootstrap.sh" ] || fail "standalone nix-portable bootstrap should not exist in image-first flow"

[ -f "${PKG_DIR}/tests/fixtures/layer6-user-env/manifest" ] || fail "missing Layer 6 smoke fixture manifest"
grep -q 'bin|rocknix-layer6-smoke' "${PKG_DIR}/tests/fixtures/layer6-user-env/manifest" || fail "Layer 6 smoke fixture missing bin target"
grep -q 'profile.d|999-rocknix-layer6-smoke' "${PKG_DIR}/tests/fixtures/layer6-user-env/manifest" || fail "Layer 6 smoke fixture missing profile.d target"
[ -f "${PKG_DIR}/tests/fixtures/layer7-apps/browser/manifest" ] || fail "missing Layer 7 browser fixture manifest"
grep -q 'bin|rocknix-layer7-browser' "${PKG_DIR}/tests/fixtures/layer7-apps/browser/manifest" || fail "Layer 7 fixture missing browser launcher target"
grep -q 'profile.d|999-rocknix-layer7-browser' "${PKG_DIR}/tests/fixtures/layer7-apps/browser/manifest" || fail "Layer 7 fixture missing browser profile.d target"
check_script "${PKG_DIR}/tests/fixtures/layer7-apps/browser/files/bin/rocknix-layer7-browser"
sh -n "${PKG_DIR}/tests/fixtures/layer7-apps/browser/files/profile.d/999-rocknix-layer7-browser" || fail "Layer 7 profile snippet syntax failed"

[ -f "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" ] || fail "missing runtime smoke test"
sh -n "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke syntax failed"
grep -q 'LAYER8_SMOKE=1' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 8 opt-in flag"
grep -q 'LAYER8_REBOOT_VERIFY' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 8 reboot verification"
grep -q 'NIX_REMOTE=daemon' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing daemon client proof"
grep -q 'nix-integration Layer 8 smoke passed' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 8 success marker"
grep -q 'LAYER9_SMOKE=1' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 9 opt-in flag"
grep -q 'LAYER9_GUEST_ROOT' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 9 guest root override"
grep -q 'systemd-nspawn guest proof' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 9 nspawn proof description"
grep -q -- '--register=no' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke must run nspawn without machined registration"
grep -q 'layer9-guest-proof' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 9 proof marker"
grep -q 'nix-integration Layer 9 smoke passed' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 9 success marker"
grep -q 'LAYER10_SMOKE' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 10 opt-in flag"
grep -q 'guest run' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 10 proof guest run path"
grep -q 'guest start' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 10 bootable start path"
grep -q 'nix-integration Layer 10 smoke passed' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 10 success marker"
grep -q 'Layer 10 bootable smoke requires provenance metadata' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 10b provenance gate"
grep -q 'LAYER11_SMOKE' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 11 opt-in flag"
grep -q 'bridge install' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 11 bridge install path"
grep -q 'bridge run' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 11 bridge run path"
grep -q 'nix-integration Layer 11 smoke passed' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing Layer 11 success marker"

# nspawn running detector: must use exec-name + cmdline scan, not the
# self-matching ps|grep idiom that masked Layer 10b/12 hardware failures.
grep -q '^nspawn_pid_for_root()' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing nspawn_pid_for_root helper"
grep -q '^nspawn_running_for_root()' "${PKG_DIR}/scripts/nixctl" || fail "nixctl missing nspawn_running_for_root helper"
if grep -q "grep '\[s\]ystemd-nspawn'" "${PKG_DIR}/scripts/nixctl"; then
  fail "nixctl still uses self-matching ps|grep '[s]ystemd-nspawn' idiom"
fi
grep -q '^smoke_nspawn_running()' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing smoke_nspawn_running helper"
if grep -q "grep '\[s\]ystemd-nspawn' | grep -F" "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh"; then
  fail "runtime smoke still uses self-matching ps|grep '[s]ystemd-nspawn' idiom"
fi
grep -q 'NSPAWN_IMPOSTOR_PID' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing self-match regression fixture for nspawn detector"

# U2 autostart-detection semantics: must use stdout-state allowlist, not
# 'is-enabled --quiet' exit-code-only check that misclassifies static units.
grep -q '^unit_autostarts()' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing unit_autostarts helper (U2)"
grep -q 'enabled|enabled-runtime|alias' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "unit_autostarts must allow only enabled/enabled-runtime/alias (U2)"
if grep -E -q 'systemctl is-enabled[^|]+>/dev/null 2>&1' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh"; then
  fail "runtime smoke still uses exit-code-only systemctl is-enabled idiom (U2)"
fi

# U3 hardware smoke runnable from packaged install layout: device-side
# sections must use resolve_smoke_bin so /usr/bin/nixctl is found at
# /usr/lib/nix-integration/tests/.
grep -q '^resolve_smoke_bin()' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing resolve_smoke_bin helper (U3)"
grep -q 'NIXCTL=\$(resolve_smoke_bin nixctl)' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke must resolve NIXCTL via resolve_smoke_bin (U3)"
grep -q 'DOCTOR=\$(resolve_smoke_bin nix-doctor)' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke must resolve DOCTOR via resolve_smoke_bin (U3)"

# U4 fixture preamble gate: HARDWARE_ONLY_MODE must reference all six CI-mode
# flags AND all three hardware-mode flags so future flag additions are caught.
grep -q 'HARDWARE_ONLY_MODE=' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing HARDWARE_ONLY_MODE gate (U4)"
for flag in LAYER4_SMOKE LAYER5_SMOKE LAYER6_SMOKE LAYER7_SMOKE LAYER8_SMOKE LAYER9_SMOKE; do
  grep -q "\"\${${flag}:-0}\" != \"1\"" "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "HARDWARE_ONLY_MODE must reject ${flag} (U4)"
done
grep -q 'LAYER10_SMOKE:-0}" != "proof"' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "HARDWARE_ONLY_MODE must reject LAYER10_SMOKE=proof (U4)"
grep -q 'LAYER10_SMOKE:-0}" = "bootable"' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "HARDWARE_ONLY_MODE must accept LAYER10_SMOKE=bootable (U4)"
grep -q 'hardware-only mode: skipping CI fixture preamble' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh" || fail "runtime smoke missing hardware-only skip note (U4)"
l11_requested_refs=$(grep -c 'LAYER11_REQUESTED' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh")
l12_requested_refs=$(grep -c 'LAYER12_REQUESTED' "${SCRIPT_DIR}/nix-integration-runtime-smoke.sh")
[ "${l11_requested_refs}" -ge 8 ] || fail "hardware Layer 11 request must survive earlier layer skip gates (U4)"
[ "${l12_requested_refs}" -ge 9 ] || fail "hardware Layer 12 request must survive earlier layer skip gates (U4)"

printf 'nix-integration static checks passed\n'
